[package]
name = "interpreter"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[lib]
name = "interpreter"
path = "src/library/library.rs"

[[bin]]
name = "interpreter"
path = "src/main.rs"
