name: Rust CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: rustup update
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Run tests
        run: make test
      - name: Run checks
        run: make check
      
